"""add_problem_metadata

Revision ID: 470a87f23d99
Revises: a299e13ceaa5
Create Date: 2026-06-20 23:58:28.357496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470a87f23d99'
down_revision: Union[str, Sequence[str], None] = 'a299e13ceaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('leetcode_id', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('status', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('solution_link', sa.String(), nullable=True))
    op.add_column('problems', sa.Column('solved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'solved_at')
    op.drop_column('problems', 'solution_link')
    op.drop_column('problems', 'notes')
    op.drop_column('problems', 'status')
    op.drop_column('problems', 'leetcode_id')
    # ### end Alembic commands ###
